name: flutter_chat_ui_starter
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  simple_animations: ^1.1.3
  page_transition: ^1.1.7+6
  firebase_core: ^1.0.3
  firebase_analytics: ^8.0.3
  firebase_auth: ^1.0.2
  firebase_storage: ^8.0.5
  cloud_firestore: ^1.0.4
  provider: ^5.0.0
  timeago: ^3.0.2
  modal_progress_hud: ^0.1.3
  flutter_slidable: ^0.6.0
  auto_direction: ^0.0.5
  image_picker: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:


  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-VariableFont_wght.ttf
